# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "."
tmp_dir = "tmp"

[build]
    # Binary file yields from `cmd`.
    bin = "./tmp/main"
    # Just plain old shell command. You could use `make` as well.
    cmd = "go build -o ./tmp/main ./cmd/server"
    # Customize binary.
    # This is how you start to run your application. Since my application will works like CLI, so to run it, like to make a CLI call.
    full_bin = ""
    # This log file places in your tmp_dir.
    log = "build-errors.log"
    # Watch these filename extensions.
    include_ext = ["go", "yaml"]
    # Ignore these filename extensions or directories.
    exclude_dir = ["tmp","logs"]
    # It's not necessary to trigger build each time file changes if it's too frequent.
    delay = 1000 # ms
    kill_delay = "0s"
    send_interrupt = false
    stop_on_error = true
    exclude_file = []
    exclude_regex = []
    exclude_unchanged = false
    follow_symlink = false

[color]
    app = ""
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"

[log]
    # Show log time
    time = false

[misc]
    # Delete tmp directory on exit
    clean_on_exit = true

[screen]
    clear_on_rebuild = true